---
# tasks file for deploy_docker_nginx
- name: install dependencies
  apt:
    name: "{{item}}"
    state: present
    update_cache: yes
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common
- name: add GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
- name: add docker repository to apt
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present
- name: install docker
  apt:
    name: "{{item}}"
    state: latest
    update_cache: yes
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io
- name: check docker is active
  service:
    name: docker
    state: started
    enabled: yes
- name: Ensure group "docker" exists
  ansible.builtin.group:
    name: docker
    state: present
- name: adding root to docker group
  user:
    name: root
    groups: docker
    append: yes
- name: Install docker-compose
  get_url:
    url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: 'u+x,g+x'
- name: Change file ownership, group and permissions
  ansible.builtin.file:
    path: /usr/local/bin/docker-compose
    owner: root
    group: root
- name: Coppy docker-compose
  copy:
    src: docker-compose.yml
    dest: /
    mode: u=rw,g=rw,o=rw
- name: Copy JPG and Index
  copy: 
    src: '{{ item }}'
    dest: /
    mode: 0644
  loop:
    - 1.jpg
    - index.html
- name: Run docker-compose
  become: true
  shell:
    cmd: "docker-compose up --build -d"   